#include "PLYWriter.h"

#include <fstream>
#include <stdexcept>

void writePLY(const char* filename, const std::vector<Vertex>& verts, const std::vector<glm::uvec3>& tries)
{
	std::ofstream file{ filename };
	if (!file.is_open()) throw new std::runtime_error("Could not open file for writing");
	file
		<< "ply\n"
		<< "format ascii 1.0\n"
		<< "comment Generated by ArrowSysMaker\n"
		<< "comment https://github.com/sgrottel/ArrowSysMaker\n"
		<< "element vertex " << verts.size() << "\n"
		<< "property float x\n"
		<< "property float y\n"
		<< "property float z\n"
		<< "property float nx\n"
		<< "property float ny\n"
		<< "property float nz\n"
		<< "property uchar red\n"
		<< "property uchar green\n"
		<< "property uchar blue\n"
		<< "element face " << tries.size() << "\n"
		<< "property list uchar int vertex_index\n"
		<< "end_header\n";
	for (auto& v : verts) {
		file << v.v.x << " " << v.v.y << " " << v.v.z << " "
			<< v.n.x << " " << v.n.y << " " << v.n.z << " "
			<< static_cast<int>(v.c.r) << " "
			<< static_cast<int>(v.c.g) << " "
			<< static_cast<int>(v.c.b) << "\n";
	}
	for (auto& t : tries) {
		file << "3 " << t.x << " " << t.y << " " << t.z << "\n";
	}

	file.close();
}
